/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "../JuceLibraryCode/JuceHeader.h"
#include "InputProcessor.h"

//==============================================================================
class AroooApplication : public JUCEApplication {
public:
  //==============================================================================
  AroooApplication() {
    inputProcessor = new InputProcessor();
  }

  const String getApplicationName() {
    return ProjectInfo::projectName;
  }

  const String getApplicationVersion() {
    return ProjectInfo::versionString;
  }

  bool moreThanOneInstanceAllowed() {
    return false;
  }

  //==============================================================================
  void initialise(const String& commandLine) {
    inputProcessor->initialize();
  }

  void shutdown() {
    if (inputProcessor) {
      delete inputProcessor;
    }
  }

  //==============================================================================
  void systemRequestedQuit() {
    // This is called when the app is being asked to quit: you can ignore this
    // request and let the app carry on running, or call quit() to allow the app to close.
    quit();
  }

  void anotherInstanceStarted(const String& commandLine) {
    // When another instance of the app is launched while this one is running,
    // this method is invoked, and the commandLine parameter tells you what
    // the other instance's command-line arguments were.
  }

private:
  InputProcessor *inputProcessor;
};

//==============================================================================
// This macro generates the main() routine that launches the app.
START_JUCE_APPLICATION (AroooApplication)
